Vagrant.configure(2) do |config|
  config.vm.box = "hashicorp/precise32"
  config.vm.network "public_network", ip: "192.168.0.53"
  
  config.berkshelf.enabled = true
  config.berkshelf.berksfile_path = "cookbooks/artifactory_server/Berksfile"
  
  config.vm.provision "chef_solo" do |chef|
    chef.add_recipe "artifactory_server"
  end
end
